# Generated by Django 4.2.6 on 2023-11-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_app_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
    ]
