# Generated by Django 4.2.6 on 2023-11-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_app_disabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="app",
            name="disabled",
        ),
        migrations.AddField(
            model_name="app",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
