# Generated by Django 4.2.6 on 2023-11-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_app_disabled_app_enabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="app",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="app",
            name="uses_api",
            field=models.BooleanField(default=False),
        ),
    ]
