# Generated by Django 4.2.6 on 2023-11-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_app_options_app_uses_api"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZulipImgRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("img_url", models.URLField(max_length=1000)),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
    ]
