# Generated by Django 4.2.6 on 2023-11-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_zulipimgrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomingZulipMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("payload", models.JSONField()),
            ],
        ),
    ]
